### PR TITLE
Update Mill to 0.11.1, migrate script to millw

### PR DESCRIPTION
**Pull request by lolgab**

### CODE REVIEW

**Comment by SethTisue** [comment]
Can you suggest a reviewer? If not, I'm happy to hit "merge".

**Comment by lolgab** [comment]
Sure! @lefou can you give a look?

**Review by lefou — APPROVED** [review]
This PR replaces the mill script with millw 0.4.7, which is a bit more complex but able to handle all older Mill versions in case someone edits the `.mill-version` file.

**Comment by lolgab** [comment]
I default to use millw as the mill script. I can also use the latest version of the official mill script which is smaller and similar to the current script.

**Pull request merged**
