### PR TITLE
Upgrade Dotty to 3.0.1

### PR DESCRIPTION
**Pull request by prolativ**

### CODE REVIEW

**Review by SethTisue — APPROVED** [review]

**Comment by prolativ** [comment]
@SethTisue could we get this merged?

**Comment by SethTisue** [comment]
I've sent you an invite to https://github.com/orgs/scala/teams/committers , so after you accept that, let me know if you aren't able to merge it yourself

**Comment by prolativ** [comment]
@SethTisue thanks, I got the invitation but this still doesn't seem to give me privileges to merge

**Comment by SethTisue** [comment]
How about now? (I added the committers team to https://github.com/scala/scala3-mill-example-project/settings/access)

**Comment by prolativ** [comment]
It works now, thanks

**Pull request merged**
